- Cargo.toml
- LICENSE
- src/celestia/mod.rs
- src/celestia/planets.rs
- src/celestia/state.rs
- src/dynamics/celestial.rs
- src/od/mod.rs
- src/od/ranging.rs
- tests/orbitaldyn.rs
- tests/stat_od/two_body.rs
This allows for faster computation (twice as fast in the test function example), and avoids having to compute the gradient and the partials matrix.
Closes #37 . Closes #32 .
> Original research: STM computation and Kalman Sensitivity now computed using Dual Numbers

- Cargo.toml
- PULL_REQUEST_TEMPLATE.md
- examples/simple_orbit_determination/src/main.rs
- src/dynamics/celestial.rs
- src/dynamics/drag.rs
- src/io/gravity.rs
- src/lib.rs
- src/propagators/error_ctrl.rs
- src/propagators/mod.rs
- src/propagators/rk.rs
- tests/drag.rs
- tests/harmonics.rs
- tests/momentum.rs
- tests/orbitaldyn.rs
- tests/propagators.rs
- tests/stat_od/two_body.rs
~42% speed improvement in the statistical orbital determination analytical STM computation (22.89 seconds on average for a one year propagation and estimation down to 12.56 seconds!).
It does not.
> Type Propagators on dynamics and error control function

- Cargo.toml
- src/dynamics/celestial.rs
- src/od/mod.rs
- src/od/ranging.rs
- tests/stat_od/two_body.rs
Minor speed improvements. The CKF example took 12.6 seconds (averaged over three runs) for a full year tests, and now only takes 12.3 seconds when switching to hyperdual ranging. When using the hyperdual STM, computation takes 14.6 seconds for that same duration. Although slightly slower (18%), I still expect this to be very valuable when starting to estimate multibody dynamics.
Upon inspection into the traits, I do not envision any other change which may help in speed. The EOMs and the gradient are computed only once and at once. Adding the `#[inline]` directive also did not help =(
No version change needed.
Closes #51
- I have updated the `VALIDATION.md` file with …
> Upgrade to hyperdual 0.3.0 (master branch)

- README.md
The current link in the README throws a 404. This simply changes it to the right MathSpec link found on nyxspace.com.
Since this does not affect any test cases, code coverage or validation, I lazily ignored the form.
> MathSpec link has moved

- .github/workflows/tests.yaml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/nyx-space/nyx/actions/runs/4139269065:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/cargo` are replaced by direct invocations of `cargo`.
> Replace unmaintained actions-rs/cargo actions in CI workflows

- README.md
- src/cosmic/cosm.rs
- src/cosmic/mod.rs
- src/cosmic/xb.rs
- src/dynamics/guidance/ruggiero.rs
- src/io/formatter.rs
- src/nav/state.rs
- src/propagators/error_ctrl.rs
- tests/propagation/stopcond.rs
This pull request fixes a few typos.
- I have updated the `VALIDATION.md` file with the new error data between nyx and GMAT.
- I will specify the version of GMAT used for the validation.
> Fix some typos

- .github/workflows/tests.yaml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/nyx-space/nyx/actions/runs/4139269065:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain).
> Replace unmaintained actions-rs/toolchain actions in CI workflows

- Cargo.toml
- src/cosmic/spacecraft.rs
- tests/propagation/stm.rs
Update Cargo.toml dependencies and switch to using `fixed_view` for STM extractions
Bump to nalgebra 0.32 and hyperdual 1.2.0, both locked versions now.
In the future, the project will used [cargo vendor](https://doc.rust-lang.org/cargo/commands/cargo-vendor.html).
> Hotfix for versioning issue

- README.md
I just added syntax highlighting in the main README file to make it easier to read.
- I have updated the `VALIDATION.md` file with the new error data between nyx and GMAT.
- I will specify the version of GMAT used for the validation.
> (doc) add synthax coloring to codeblocks

- .github/workflows/tests.yaml
- Cargo.toml
- src/od/kalman.rs
- src/od/mod.rs
- src/od/msr/mod.rs
- src/od/process/mod.rs
- src/od/process/rejectcrit.rs
- src/od/residual.rs
- src/python/orbit_determination/mod.rs
- src/python/orbit_determination/process.rs
- tests/orbit_determination/mod.rs
- tests/orbit_determination/multi_body.rs
- tests/orbit_determination/resid_reject.rs
- tests/orbit_determination/robust.rs
- tests/orbit_determination/spacecraft.rs
- tests/orbit_determination/two_body.rs
- tests/orbit_determination/xhat_dev.rs
Add the ability to reject measurements online prior to ingesting them in the filter. When rejected, a warning is printed and the filter performs a time update instead.
TODO:
Closes #127
> Add online measurement rejection

- Cargo.toml
- src/cosmic/mod.rs
- src/cosmic/orbit.rs
- src/dynamics/guidance/ruggiero.rs
- src/errors.rs
- src/io/trajectory_data.rs
- src/mc/results.rs
- src/md/trajectory/orbit_traj.rs
- src/polyfit/hermite.rs
- src/python/mission_design/spacecraft.rs
- tests/python/test_mission_design.py
+ Prevent duplicate epochs in OEM loading
+ Add reason for state parameter errors
+ In Python, make orbit epoch and Cartesian data available as getters
+ Maybe added the `==` in Python for Orbit, it doesn't always seem to work for some reason
Womp womp
> Fix trajectory loading from Python

- .vscode/settings.json
- src/utils.rs
Simplify some functions from `src/utils.rs` and add more UTs.
- `between_0_360`: in this version, we use the modulo operator (%) to obtain the remainder of the division of the angle by 360.0. This gives us a number that is necessarily less than 360.0. If this number is negative (which can happen if the angle is negative), we add 360.0 to make it positive. This function therefore always returns a number between 0.0 and 360.0, as desired.
- `between_pm_x`: this version also uses the modulo operator to normalize the angle, which is more efficient than using a while loop. The unit tests cover several cases: a positive angle greater than x, a negative angle less than -x, an angle already within the interval [-x, x), an angle of zero degrees and an angle of 360 degrees.
- `is_diagonal`: less …
> Simplify `between_0_360` & `between_pm_x` from `src/utils.rs`

- src/utils.rs
- Improved docstrings: more detail and better rendering in the IDE (VSCode at least)
- Added some unit tests
> (doc/test) improve `r1/r2/r3` rotation matrix

- src/utils.rs
- Improve docstrings on `rss_*` utility functions from `utils.rs`
- Make `rss_errors` kind of more idiomatic using a functional programming way
I tried to put some UT but I did not well understood how to do them.
For example, we could have:
```rs
#[test]
fn test_rss_errors() {
let prop_err = OVector::from_vec(vec![1.0, 2.0, 3.0]);
let cur_state = OVector::from_vec(vec![1.0, 2.0, 3.0]);
assert_eq!(rss_errors(&prop_err, &cur_state), 0.0);
let prop_err = OVector::from_vec(vec![1.0, 2.0, 3.0]);
let cur_state = OVector::from_vec(vec![4.0, 5.0, 6.0]);
assert_eq!(rss_errors(&prop_err, &cur_state), 5.196152422706632);
}
```
But I currently have some compiler complains about `from_vec`, so I gave up and trust the CI.
I hope to get feedback from you on this subject!
> (feat) improve `rss_errors()` using a functional programming approach

- src/utils.rs
The following is a revised version of the `are_eigenvalues_stable` function with improved documentation, a clearer code structure and unit tests.
> (feat) refactor `are_eigenvalues_stable`

- src/utils.rs
This PR adds one test case to `is_diagonal` test suite where we have a diagonal with on zero/null element.
> (test) add UT case "diagonal with zero diagonal element"

- src/utils.rs
This PR introduces several improvements to the vector operations, normalization and capitalization functions.
The changes are intended to make the code more idiomatic Rust, improve readability, and enhance the robustness of the code.
1. Refactored the `rotv`, `perpv`, and `projv` functions to use more idiomatic Rust. This includes using the `normalize`, `scale`, `cross`, `dot`, `amax`, `sub`, and `norm_squared` methods from the `Vector3` struct.
2. Refactored the `normalize`, `denormalize`, and `capitalize` functions.
3. Improved the documentation for these functions. Each function now has a detailed docstring that describes its purpose, its arguments, and its return value. This will make it easier for other developers to understand and use these functions.
4. Added comprehensive unit …
> Improve Vector Operations, Normalization and Capitalization

- src/tools/lambert.rs
To ease readability - too many lines so to save mental load of the reader.
> (feat) breakdown Lambert::stardard() function

- src/utils.rs
Some improvements we could make to make the code more idiomatic in Rust.
- Use direct indexing to access vector elements rather than using tuples.
- Improved documentation to explain what the function does and what it returns.
> (feat) make `tilde_matrix` (skew-symmetric matrix) more idiomatic

- .github/workflows/rust.yaml
- src/od/simulator/trackdata.rs
- src/utils.rs
The doc tests were broken because they aren't checked until the coverage test. This PR fixes that.
> Fix doc tests

- src/md/param.rs
Until this, state parameters did not include units. This fixes it. Eventually I might want to switch this to be in the base unit instead of the unit used in Nyx, because that would look better on the plots, but maybe that's something specific to plotting.
> Add units to all state parameters

- Cargo.toml
- src/md/trajectory/orbit_traj.rs
Prevents the OEM parser from crashing if it can't parse the line. Also prevents parsing the covariance data. This will be supported in #87 .
> Prevent parsing of covariance

- .gitignore
- src/cosmic/mod.rs
- src/mc/montecarlo.rs
- src/md/opti/raphson_finite_diff.rs
- src/md/opti/raphson_hyperdual.rs
- src/md/trajectory/orbit_traj.rs
- src/md/trajectory/sc_traj.rs
- src/propagators/instance.rs
All uses of `std::Instant` are now limited to targets other than `wasm32-*`. 
There should be no effect for targets other than WASM.
When targeting WebAssembly, it is now possible to use this library in environments where a time API is not available. For more details, see the original comment in #204 
- I have updated the `VALIDATION.md` file with the new error data between nyx and GMAT.
- I will specify the version of GMAT used for the validation.
> Limit usage of std::Instant to non-wasm targets

- src/md/trajectory/traj.rs
- src/python/mission_design/orbit_trajectory.rs
- src/python/mission_design/sc_trajectory.rs
- tests/python/test_mission_design.py
Allows for this from Python:
```python
traj1_moon = traj1.to_frame("Moon J2000")
traj2_moon = traj2.to_frame("Moon J2000")
traj_moon = traj1_moon + traj2_moon
```
This feature was already available in Rust.
1. The addition operator in Rust now returns a Result type after checking for the frame. Prior to this PR, it was possible to add two trajectories in different frames.
2. The order of addition matters: with `self+rhs`, only the states whose epoch is greater than `self.last().epoch` are added to the trajectory, so if there is an overlap in epochs, the order of the addition matters.
> Export trajectory addition and frame conversion to Python

- python/nyx_space/analysis/__init__.py
- python/nyx_space/analysis/traj.py
- python/nyx_space/plots/traj.py
- src/md/trajectory/traj.rs
- src/python/mission_design/sc_trajectory.rs
- tests/python/test_mission_design.py
- tests/python/test_orbit_determination.py
> Plot trajectory in ric frame

- .github/workflows/python.yml
- .gitignore
- Cargo.toml
- python/nyx_space/plots/utils.py
- src/cosmic/orbit.rs
- src/cosmic/spacecraft.rs
- src/dynamics/spacecraft.rs
- src/io/mod.rs
- src/io/trajectory_data.rs
- src/md/trajectory/traj.rs
- src/od/ground_station.rs
- src/od/noise/gauss_markov.rs
- src/od/process/rejectcrit.rs
- src/od/simulator/arc.rs
- src/od/simulator/trkconfig.rs
- src/python/mission_design/spacecraft.rs
- src/python/mod.rs
- src/python/orbit_determination/arc.rs
- src/python/orbit_determination/estimate.rs
- src/python/orbit_determination/ground_station.rs
- src/python/orbit_determination/mod.rs
- src/python/orbit_determination/trkconfig.rs
- src/python/pyo3utils/mod.rs
- tests/python/test_cosmic.py
- tests/python/test_mission_design.py
- tests/python/test_orbit_determination.py
- tests/python/test_yaml.py
One can now pickle the following data:
- TrkConfig
- FltResid
- GaussMarkov
- GroundStation
- Spacecraft
- SRPConfig
- DragConfig
The following structures can now be _loaded_ from YAML read by Python but not exported:
- OrbitEstimate
- SpacecraftDynamics
Moreover, the `==` in Python is now correctly supported wherever it was incorrect set up.
> Support pickling of a number of important structures to Python

- .github/workflows/performance.yaml
- src/od/process/mod.rs
Only for monitoring and catching large changes in behavior.
The workflow should run only on the master branch and on request.
Closes #223
> Measure performance with flamegraph

- src/cosmic/cosm.rs
- src/cosmic/mod.rs
- src/dynamics/spacecraft.rs
- src/md/trajectory/orbit_traj.rs
> Fix clippy lints

- Cargo.toml
+ Hifitime in 3.8.5
+ PyO3 in 0.20
+ Numpy in 0.20
+ Pythonize in 0.20
> Update to hifitime 3.8.5, PyO3 to 0.20

- .github/workflows/python.yml
- .github/workflows/rust.yaml
Trying to release to pypi... Requires manylinux which can't easily be run locally.
> Trying to allow re-release manually

- Cargo.toml
- src/python/orbit_determination/process.rs
- tests/orbit_determination/resid_reject.rs
- tests/orbit_determination/robust.rs
- tests/propagation/events.rs
- tests/python/test_cosmic.py
- tests/python/test_mission_design.py
- tests/python/test_orbit_determination.py
Add SNC configuration to Python API.
> Expose SNC configuration to Python

- tests/orbit_determination/xhat_dev.rs
All the tests to pass on Github Actions.
> Increase tolerance on xhat dev test

- src/dynamics/drag.rs
Updates to drag units to convert from ((kg * km^2 * s^-2) / m^1) to (kg * km * s^-2)
> Updates to drag units

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/daily.yaml
- .github/workflows/rust.yaml
Codecov seems to have issues with open-source projects, so I'm not sure if this will work.
- I have updated the `VALIDATION.md` file with the new error data between nyx and GMAT.
- I will specify the version of GMAT used for the validation.
> Try to switch to llvm-cov for coverage

- src/cosmic/orbitdual.rs
- src/cosmic/spacecraft.rs
- src/dynamics/drag.rs
- src/dynamics/mod.rs
- src/dynamics/solarpressure.rs
- src/dynamics/spacecraft.rs
- src/od/filter/kalman.rs
- src/od/msr/range_doppler.rs
- src/od/process/mod.rs
- tests/orbit_determination/spacecraft.rs
This change enables the estimation of Cr and Cd in the orbit determination of Nyx. This change has long been coming.
The SRP estimation model is **finicky.** You will NEED to enable some level of state noise compensation. The ODTK MathSpec (page 179) recommends modeling the SRP as a first order Gauss Markov process, which accounts for the time between measurements to even out the partial of the Cr. Instead, _Nyx estimates Cr directly_, assuming that it is a fixed value. This means that the filter is _very_ (too?) responsive to changes in Cr. Too much SNC, and the Cr estimation does not happen because the changes are absorbed by the SNC, and too little, and you'll end up with a very slow estimation, and a Cr value that fluctuates a lot.
Implementations of `ForceModel` now return a …
> Support estimation of spacecraft coefficient of reflectivity and drag

- examples/01_orbit_prop/main.rs
- examples/02_jwst_covar_monte_carlo/main.rs
- examples/03_geo_analysis/drift.rs
- examples/03_geo_analysis/raise.rs
- examples/03_geo_analysis/stationkeeping.rs
- examples/04_lro_od/main.rs
- src/cosmic/eclipse.rs
- src/dynamics/guidance/ruggiero.rs
- src/dynamics/solarpressure.rs
- src/dynamics/sph_harmonics.rs
- src/od/ground_station.rs
- tests/cosmic/eclipse.rs
- tests/lib.rs
- tests/mission_design/force_models.rs
- tests/propagation/events.rs
- Upgrades for ANISE 0.4.3: https://github.com/nyx-space/anise/releases/tag/0.4.3
Improvements in the computation of eclipsing lead to significant improvements of the solar radiation pressure modeling when compared to GMAT:
```
Error accumulated in full sunlight over 24 days : 0.488737 m 	0.000081 m/s
test mission_design::force_models::srp_earth_full_vis ... ok
Error accumulated in ecc+inc MEO (with penumbras) over 24 days : 1.866381 m 	0.000635 m/s
Error accumulated in circular equatorial LEO (with penumbras) over 24 days : 5.989316 m 	0.006456 m/s
test mission_design::force_models::srp_earth_leo ... ok
```
Note that some of these changes could be due to the improvements in the ephemeris itself by using ANISE in the first place, but I don't think so because I'm pretty sure I had checked …
> Upgrade to anise 0.4.3

- src/dynamics/sph_harmonics.rs
Updated harmonics calculations using `Vector4`
No change
No change
Leveraged `Vector4` for acceleration and sum terms of Pines' algorithm. Slight performance improvement expected. 
No change
No change
All tests passing
This PR does not primarily deal with documentation changes.
> Consolidated accel and sum into Vector4

- src/propagators/instance.rs
- src/propagators/mod.rs
- src/propagators/options.rs
- tests/orbit_determination/spacecraft.rs
The minimum step check was sometimes bypassed when updating the step size for the next integration cycle. This could cause the minimum integration step size to be zero, thereby hanging forever. This PR also prevents NaN from showing up in the solution of an integration by stopping the integration and recommending solutions.
This PR fixes #377 where this bug was identified. Thanks @gregjesl !
No change
No change
Propagation reporting now shows the current step size as well.
Integrator steps are now always within integrator option bounds.
No changes to the test themselves, but I tested the fix on the code from the bug report.
This PR does not primarily deal with documentation changes.
> Bound the proposed integrator steps

- src/md/events/mod.rs
Added event template for detecting central body collisions. 
No change
Added a method for generating an event that detects when an orbit crosses the mean equatorial radius of a central body. This is useful for approximating when an object might impact the central body. 
No change
Simplifies the search for trajectories that might impact the central body. 
No change
No change
Tested in simulation. 
This PR does not primarily deal with documentation changes.
> Added template method for mean surface event

- examples/04_lro_od/main.rs
Fixes mismatch between comments and implementation
No change
No change
No change
No change
No change to code
Original comment stated
https://github.com/nyx-space/nyx/blob/1378c5b9065c82f7145891ba0b03038fef25da9a/examples/04_lro_od/main.rs#L89
but actual arguments are
https://github.com/nyx-space/nyx/blob/1378c5b9065c82f7145891ba0b03038fef25da9a/examples/04_lro_od/main.rs#L95-L97
which is a five-second interval over 24 hours, not a one-minute interval over 48 hours.
> Aligned comment with trajectory arguments

- Cargo.toml
- README.md
- data/tests/config/high-prec-network.yaml
- data/tests/config/many_ground_stations.yaml
- data/tests/config/one_ground_station.yaml
- examples/04_lro_od/plot_od_rslt.py
- src/cosmic/orbitdual.rs
- src/dynamics/guidance/ruggiero.rs
- src/lib.rs
- src/mc/dispersion.rs
- src/md/events/details.rs
- src/md/events/mod.rs
- src/md/objective.rs
- src/od/filter/kalman.rs
- src/od/ground_station/trk_device.rs
- src/od/msr/measurement.rs
- src/od/msr/trackingdata/io_ccsds_tdm.rs
- src/od/msr/trackingdata/io_parquet.rs
- src/od/msr/trackingdata/mod.rs
- src/od/msr/types.rs
- src/od/noise/gauss_markov.rs
- src/od/noise/mod.rs
- src/od/noise/white.rs
- src/od/process/mod.rs
- src/od/process/trigger.rs
- src/od/simulator/arc.rs
- src/od/simulator/trackdata.rs
- src/propagators/mod.rs
- tests/orbit_determination/simulator.rs
- Support ambiguity resolution as per JPL DESCANSO [214 - Pseudo-Noise and regenerative ranging](https://deepspace.jpl.nasa.gov/dsndocs/810-005/214/214C.pdf)
- Support moduli as per CCSDS TDM Blue Book
- Fix path in Nyx-built TDMs, accounting for whether the measurement type is one or two way, fixes #397 
- Add serde for (most) every input, outputs (like event evaluations) should still go in parquet, fixes #396 
- Add moduli to tracking data arc
- Add optional constant to stochastic models
- Accounts for ambiguity resolution / modulus in orbit determination
No change
- Fix TDM parsing for two-way measurements
As per #397 :
Simulate a tracking arc with the JPL DSN Code whose modulus is 75660 km. To ensure testing of the ambiguity intervals, fix the `apply_moduli` function to account for …
> Orbit determination constant biases + measurement ambiguity and moduli

- Cargo.toml
- src/od/estimate/residual.rs
- src/od/filter/kalman.rs
- src/od/filter/mod.rs
- src/od/process/export.rs
- src/od/process/mod.rs
- tests/orbit_determination/mod.rs
**Breaking changes:**
1. `measurement_update` now owns the real and computed observations
2. Residual now include a copy of the real and computed observations, enabling all runs to also plot the residual versus reference when disabling measurements from a specific arc.
Also fixes a zero norm measurement when such measurement is not available in the tracker but is available in the measurement data.
1. `measurement_update` now owns the real and computed observations -- this enables the following item
2. Residual now include a copy of the real and computed observations.
Residual now include a copy of the real and computed observations, enabling all runs to also plot the residual versus reference when disabling measurements from a specific arc.
No change
Fix #410
**Detail the changes in …
> Fix zero measurement observation

- Cargo.toml
- README.md
- src/od/msr/trackingdata/mod.rs
- src/od/noise/link_specific.rs
- src/od/noise/mod.rs
- tests/orbit_determination/measurements.rs
- Add the `premium` crate feature, along with documentation in the README about who it affects
- Add link specific noise modeling for OD: specify the carrier frequency, S/N0, etc. and it'll build a high precision Range and Doppler noise model (without accounting to tropospheric and ionospheric errors)
- Validate existing noise modeling
No change
- Add link specific noise modeling for OD: specify the carrier frequency, S/N0, etc. and it'll build a high precision Range and Doppler noise model (without accounting to tropospheric and ionospheric errors)
- Add filtering of tracking data by measurement type
No change
No change
- Validate noise modeling, and export it to parquet
Not the most useful plot but it's still obviously white noise.
Here is the real test: check that we're in the 99.7% …
> Add link specific orbit determination noise modeling (premium feature) + validate existing noise modeling

- tests/orbit_determination/interlink.rs
- tests/orbit_determination/predict_validation.rs
- tests/utils/plot_od_orbital_elements.py
- tests/utils/plot_od_rslt.py
- tests/utils/plot_orbital_elements.py
- Tuned the interlink filter when dispersions are enable
- Added a orbital element covariance plotting tool
No change
Test utils now includes covariance plots with whichever sigma count the user wants. Add RIC error plots to the OD plotter.
No change
No change
Here come the plots!
_Note that the first measurement immediately corrects the filter_
In practice, one would probably restart the filter after it converges here to reduce the noise level and have the residual ratios fill up the whole 3 sigma bounds.
This shows that we don't have good crosstrack visibility on this CAPS-like interlink.
This shows that for about 45 minutes, the filter hasn't converged yet so it is making pretty large adjustments, but quickly converges on a solution.
This PR does not primarily deal with documentation …
> Tuned the interlink filter when dispersions enabled

- tests/orbit_determination/blse.rs
- tests/orbit_determination/multi_body.rs
- tests/orbit_determination/robust.rs
- tests/orbit_determination/simulator.rs
- tests/orbit_determination/trackingarc.rs
- tests/orbit_determination/two_body.rs
This commit updates and removes obsolete, incorrect, or unclear comments across all of the test files in the `tests/orbit_determination` directory.
This includes:
- Removing several instances of the obsolete "on one thread" comment.
- Correcting misleading comments about test configurations (e.g., noise models, invalid setups).
- Removing confusing comments that were out of sync with the code.
> Chore: Update obsolete comments in OD tests
